"use client";

import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Skeleton } from "@/components/ui/skeleton";
import { Info } from "lucide-react";
import type { VideoSummaryResponse } from "@/lib/types";

export function SummaryView({
  summary,
  isLoading,
}: {
  summary?: VideoSummaryResponse;
  isLoading?: boolean;
}) {
  if (isLoading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-6 w-3/4" />
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-40 w-full" />
      </div>
    );
  }

  if (!summary) {
    return (
      <p className="text-muted-foreground text-center py-8">
        No summary available for this video.
      </p>
    );
  }

  return (
    <div className="space-y-6">
      {/* AI Disclaimer */}
      <div className="flex items-start gap-2 rounded-lg border border-muted bg-muted/50 px-4 py-3 text-sm text-muted-foreground">
        <Info className="h-4 w-4 mt-0.5 shrink-0" />
        <p>
          This summary was generated by AI and may contain inaccuracies.
          Please refer to the original video for authoritative content.
        </p>
      </div>

      {/* Overview */}
      {summary.summary_intro && (
        <p className="text-base leading-relaxed">{summary.summary_intro}</p>
      )}

      {/* Key Points — right below overview */}
      {summary.bullets.length > 0 && (
        <div className="space-y-2">
          {summary.bullets.map((bullet, i) => (
            <div
              key={i}
              className="flex gap-3 rounded-lg border px-4 py-3"
            >
              <span className="text-primary font-semibold shrink-0">
                {i + 1}.
              </span>
              <div className="min-w-0">
                <p className="font-medium">{bullet.title}</p>
                <p className="text-sm text-muted-foreground mt-0.5">
                  {bullet.description}
                </p>
              </div>
              {bullet.timestamp && (
                <span className="text-xs font-mono text-muted-foreground mt-0.5 shrink-0 ml-auto">
                  {bullet.timestamp}
                </span>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Topics + Meta — compact row */}
      <div className="flex flex-wrap items-center gap-x-6 gap-y-3 text-sm">
        {summary.topics.length > 0 && (
          <div className="flex flex-wrap gap-1.5">
            {summary.topics.map((topic) => (
              <Badge key={topic} variant="secondary">
                {topic}
              </Badge>
            ))}
          </div>
        )}
        {summary.content_type && (
          <span className="text-muted-foreground">
            Type: <span className="text-foreground">{summary.content_type}</span>
          </span>
        )}
        {summary.target_audience && (
          <span className="text-muted-foreground">
            Audience: <span className="text-foreground">{summary.target_audience}</span>
          </span>
        )}
        {summary.tone && (
          <span className="text-muted-foreground">
            Tone: <span className="text-foreground">{summary.tone}</span>
          </span>
        )}
      </div>

      {/* Detailed Timeline (sections) — collapsible */}
      {summary.sections.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Detailed Timeline</h3>
          <Accordion className="w-full">
            {summary.sections.map((section, i) => (
              <AccordionItem key={i} value={`section-${i}`}>
                <AccordionTrigger>
                  <div className="flex items-center gap-3 text-left">
                    {section.timestamp && (
                      <span className="text-xs font-mono text-muted-foreground shrink-0">
                        {section.timestamp}
                      </span>
                    )}
                    <span>{section.title}</span>
                  </div>
                </AccordionTrigger>
                <AccordionContent>
                  <p className="text-muted-foreground whitespace-pre-line">
                    {section.content}
                  </p>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      )}

      {/* Mentions */}
      {summary.mentions.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-3">Mentions</h3>
          <div className="flex flex-wrap gap-2">
            {summary.mentions.map((mention) => (
              <Badge key={mention} variant="outline">
                {mention}
              </Badge>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
