export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-8 space-y-8">
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="text-muted-foreground">Last updated: March 15, 2026</p>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">1. Service Overview</h2>
        <p>
          Tube Agent (&quot;the Service&quot;) provides AI-powered analysis of
          publicly available YouTube channel data. The Service is intended for
          informational and research purposes only.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">
          2. AI-Generated Content Disclaimer
        </h2>
        <p>
          All analyses, summaries, reports, and insights generated by this
          Service are produced by artificial intelligence and may contain
          inaccuracies, errors, or misinterpretations. The Service does not
          guarantee the accuracy, completeness, or reliability of any
          AI-generated content. Users should independently verify any
          information before making decisions based on it.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">
          3. YouTube Content Attribution
        </h2>
        <p>
          All original YouTube content — including video titles, descriptions,
          and channel information — remains the intellectual property of the
          respective content creators. This Service accesses publicly available
          data through the YouTube Data API and does not claim ownership of any
          third-party content.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">
          4. Data Collection and Retention
        </h2>
        <p>
          The Service collects publicly available data from the YouTube Data
          API, including channel metadata, video statistics, and public
          comments. In compliance with YouTube API Terms of Service, raw API
          data is retained for a maximum of 30 days, after which statistical
          data is automatically purged. AI-generated analyses and reports, as
          derivative works, may be retained longer.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">5. Prohibited Use</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>
            Automated scraping or crawling of the Service beyond normal usage
          </li>
          <li>
            Redistribution or resale of data obtained through the Service
          </li>
          <li>
            Using the Service to harass, defame, or infringe upon the rights
            of content creators
          </li>
          <li>
            Attempting to reverse-engineer or circumvent any security measures
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">
          6. Service Modifications and Termination
        </h2>
        <p>
          We reserve the right to modify, suspend, or discontinue the Service
          at any time without prior notice. We may also update these Terms of
          Service from time to time. Continued use of the Service after changes
          constitutes acceptance of the updated terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">7. Limitation of Liability</h2>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY
          KIND. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE
          FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES
          ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO
          LOSS OF PROFITS, DATA, OR BUSINESS OPPORTUNITIES.
        </p>
      </section>
    </div>
  );
}
